server:
  port: 8081

spring:
  application:
    name: rabbit-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#eureka
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://biba:biba@localhost:8000/eureka